# Definitions:
# - Language Models: AI models designed to understand and generate human-like text based on input prompts.
# - Embedding Models: Models that convert text into numerical vectors, capturing semantic meaning for tasks like similarity analysis.
# - Base Models: Foundational models trained on large datasets, serving as the backbone for specialized tasks.

Language Models:
  - name: GPT-4
    models:
      - name: gpt-4
        pricing_info: https://openai.com/pricing
        input_cost: 0.03  # $0.03 per 1,000 prompt tokens
        output_cost: 0.06  # $0.06 per 1,000 completion tokens
        per_token: 1000
      - name: gpt-4-32k
        pricing_info: https://openai.com/pricing
        input_cost: 0.06  # $0.06 per 1,000 prompt tokens
        output_cost: 0.12  # $0.12 per 1,000 completion tokens
        per_token: 1000
    features:
      - High accuracy and advanced reasoning
      - Supports large-scale enterprise applications

  - name: Claude 3
    models:
      - name: claude-3-sonnet
        pricing_info: https://www.anthropic.com/claude/sonnet
        input_cost: 0.003  # $0.003 per 1,000 prompt tokens
        output_cost: 0.015  # $0.015 per 1,000 completion tokens
        per_token: 1000
      - name: claude-3-opus
        pricing_info: https://www.anthropic.com/claude/sonnet 
        input_cost: 0.005  # $0.005 per 1,000 prompt tokens
        output_cost: 0.025  # $0.025 per 1,000 completion tokens
        per_token: 1000
    features:
      - Ideal for complex task handling and API integrations
      - High performance with nuanced understanding

  - name: Google PaLM 2
    models:
      - name: text-bison-001
        pricing_info: https://cloud.google.com/vertex-ai/pricing#generative_ai_models
        input_cost: 0.0005  # $0.0005 per 1,000 characters
        output_cost: 0.001  # $0.001 per 1,000 characters
        per_token: 1000 # Characters are roughly equivalent to tokens
      - name: chat-bison-001
        pricing_info: https://cloud.google.com/vertex-ai/pricing#generative_ai_models
        input_cost: 0.001  # $0.001 per 1,000 characters
        output_cost: 0.002  # $0.002 per 1,000 characters
        per_token: 1000 # Characters are roughly equivalent to tokens
    features:
      - Highly capable and versatile for various tasks
      - Strong in reasoning, coding, and translation


Base Models:
  - name: OpenAI Base
    models:
      - name: davinci-002
        pricing_info: https://openai.com/pricing
        input_cost: 0.02  # $0.02 per 1,000 tokens
        per_token: 1000
      - name: curie-002
        pricing_info: https://openai.com/pricing
        input_cost: 0.002  # $0.002 per 1,000 tokens
        per_token: 1000
    features:
      - Suitable for custom fine-tuning
      - Used as foundational models for enterprise solutions